### ISSUE TITLE
TypeError: mean() received an invalid combination of arguments

### ISSUE THREAD

**Issue by cumthxy** [adobe/Deep-Audio-Prior#4]
a = torch.mean(x, (1,2,3))
TypeError: mean() received an invalid combination of arguments - got (Tensor, tuple), but expected one of:

**Comment by YapengTian** [comment]
More details?

**Comment by YapengTian** [comment]
The issue is probably from the wrong size of x. Please make sure that you provide the correct input.

**Comment by DrSleep** [comment]
This error occurs when trying to run the first example from README: 
`python dap_sep.py --input_mix data/sep/violin_basketball.wav --output output/sep`

It happens because in `requirements.txt` the specified version of pytorch is `0.4.1`, which does not support torch.mean across multiple dimensions at once - [see docs](https://pytorch.org/docs/0.4.1/torch.html#torch.mean). The correct version of pytorch should at least be [1.1.0](https://pytorch.org/docs/1.1.0/torch.html#torch.mean).

Please update either the requirements file or the provided example

**Comment by YapengTian** [comment]
Done. Thanks!

**Comment by ludwigwittgenstein2** [comment]
@DrSleep : I seem to have same issue, not able to fix it. I have Pytorch -- 1.11.0+cu113

Suggestions?
